grafana:
  enabled: true
  adminPassword: "admin"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

# Alert example (simple rule)
prometheusRule:
  rules:
    - alert: PodDown
      expr: kube_pod_status_phase{phase="Failed"} > 0
      for: 30s
      labels:
        severity: "critical"
      annotations:
        summary: "Pod is down"
        description: "Pod failed in namespace {{ $labels.namespace }} (pod: {{ $labels.pod }})"
