apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app
  namespace: monitoring
  labels:
    release: kps      # Должно совпадать с лейблом релиза Prometheus
spec:
  selector:
    matchLabels:
      app: test-app
  endpoints:
    - port: http
      interval: 15s
