apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: monitoring
  labels:
    app: test-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: test-app
